custom-server-port:

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    hostname: eureka${server.port} #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    #清除间隔时间(毫秒)
    eviction-interval-timer-in-ms: 2000

---
spring:
  config:
    activate:
      on-profile: uereka7001

server:
  port: 7001

---
spring:
  config:
    activate:
      on-profile: uereka7002

server:
  port: 7002