spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.164:1433;databaseName=MZ_TEMP_TEST
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.mz.springcloud.api.entities    # 所有Entity别名类所在包